### PR TITLE
feat: add install script

### PR DESCRIPTION
**Pull request by Ioulan**
Hello,

Uhm, what the script does, is dynamically applied the selected flavour, and import/download the preset on the proper directory.

I know that [gogh](https://github.com/Gogh-Co/Gogh) exist but still, I just make this script just for fun.

### CODE REVIEW

**Comment by sgoudham** [comment]
Hey :wave: 

Thanks for your work on this. That being said, I'm not a fan of introducing extra complexity into a codebase purely for ease of installation through a bash script.

I think this method of installation is, as you said, _fun_ but it's an extra burden on the maintainer and not to mention how the colours are being redefined again so a simple update turns into an update in 2 different locations.

**Comment by lime-desu** [comment]
Oh, yeah I've redefinded that  colorchemes, but that thing is some sort of hacky way to immediately apply the colorschemes and will only work if they have `xfconf-query` command available,  without the user going to preferences choosing the theme manually. 

I've gotta admit those are PITA In fact I asked the LLM to format that thing for me 😅. I was searching for some XFCE command to apply terminal presets colorscheme, but to no avail  so this is what the solution I've come.

**Comment by Ioulan** [comment]
> Hey 👋
> 
> Thanks for your work on this. That being said, I'm not a fan of introducing extra complexity into a codebase purely for ease of installation through a bash script.
> 
> I think this method of installation is, as you said, _fun_ but it's an extra burden on the maintainer and not to mention how the colours are being redefined again so a simple update turns into an update in 2 different locations.

Hi, Thanks for the insights!!  I've refactored the installation script and I do think, it is now somehow easy to maintain

**Comment by sgoudham** [comment]
> Hi, Thanks for the insights!! I've refactored the installation script and I do think, it is now somehow easy to maintain

Hey, yeah my honest opinion is that I really want to avoid installation bash scripts for something as simple as downloading 4 files to a directory. I should have been more direct in my first comment, sorry for that.

If someone wants to automatically install the themes, I don't think it takes much effort for them to whip up something like this:

```bash
for f in latte frappe macchiato mocha; do curl -LO "https://raw.githubusercontent.com/catppuccin/xfce4-terminal/main/src/catppuccin-$f.theme"; done
```
which pulls down all four files and then they can choose the theme via preferences in the terminal.

I know you've put effort into this, but I hope you can understand where I'm coming from here. I don't really think we should be upstreaming scripts like this, and I'll be closing this now.

**Comment by Ioulan** [comment]
Yep my I bad, I understand your perspective, I know it's as simple as doing curl/wget command to download it and makes it straightforward,  and yeah My goal is just to reduce human interferance, but then again it just as simple as right clicking navigating to preferences and yeah idk why i make my life so complicated for doing such trivial task.

**Pull request closed without merging**
